--- LIST SCHEMAS
SHOW SCHEMAS;

--- LIST TABLES
SHOW ALL TABLES;

--- SOME TABLES
SELECT * FROM RAW.RAW_BTCUSDT_D1 LIMIT 10;

SELECT * FROM DEV.BTCUSDT_D1 LIMIT 10;

--- DROPPING WHOLE DEV
DROP SCHEMA DEV CASCADE;

--- SOME TESTS
SELECT * FROM RAW.RAW_BTCUSDT_D1 WHERE Open IS NULL;